### ISSUE TITLE
Dot Code School Suggestion: Feedback for Section 1 - Chapter 9: COLLECTIVES System Chain

### ISSUE THREAD

**Issue by hippiestank** [wirednkod/papi-intro-tutorial#4]
Information in README is written twice.

**Comment by wirednkod** [comment]
Thank you @hippiestank for this. Can you point to which README file you refer to? (which step)

**Comment by hippiestank** [comment]
step 14: https://github.com/wirednkod/papi-intro-tutorial/tree/main/steps/14

**Comment by wirednkod** [comment]
Fixed
